services:
  todolistapi:
    container_name: todolistapi
    image: luara/todolistapi:1.0.0
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      XDEBUG_MODE: coverage
  
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}